# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "platform-tfstate-account-sandbox"
    dynamodb_table = "platform-tfstate-account-sandbox"
    encrypt        = true
    key            = "rotation-lambda/./dev/us-east-1/terraform.tfstate"
    region         = "eu-central-1"
  }
}
