---
name: Setup Demo

on:
    workflow_dispatch:
        inputs:
            option:
                description: Either 'Create' or 'Destroy' is allowed.
                required: true
                default: Create
                type: choice
                options:
                    - Create
                    - Destroy

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: us-east-1

jobs:
    run-cli:
        runs-on: ubuntu-latest
        steps:
            - name: Check out current repository
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.20

            - name: Compile Dagger pipeline
              working-directory: pipeline/dagger
              run: |
                  go mod tidy
                  go build -o pipeline-dagger
                  if [ -f "../../pipeline-dagger" ]; then rm ../../pipeline-dagger; fi
                  mv pipeline-dagger ../../pipeline-dagger


            - name: Deploy Demo Secret
              if: ${{ github.event.inputs.option == 'Create' }}
              run: ./pipeline-dagger infra --component=secret --plan
