---
name: Setup Demo Config

on:
    workflow_dispatch:
        inputs:
            option:
                description: Either 'Create' or 'Destroy' is allowed.
                required: true
                default: Create
                type: choice
                options:
                    - Create
                    - Destroy

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: us-east-1

jobs:
    rotator-ci:
        name: Rotator CI
        runs-on: ubuntu-latest
        steps:
            - name: Check out current repository
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '>=1.20.0'

            - name: Compile Dagger pipeline
              working-directory: pipeline/dagger
              run: |
                  go mod tidy
                  go build -o pipeline-dagger
                  if [ -f "../../pipeline-dagger" ]; then rm ../../pipeline-dagger; fi
                  mv pipeline-dagger ../../pipeline-dagger


            - name: Compile
              if: ${{ github.event.inputs.option == 'Create' }}
              run: ./pipeline-dagger lambda --compile --lambda-src=src/lambda/secrets-manager-rotator-go
