---
name: Setup Demo Config

on:
    workflow_dispatch:
        inputs:
            option:
                description: Either 'Create' or 'Destroy' is allowed.
                required: true
                default: Create
                type: choice
                options:
                    - Create
                    - Destroy

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: us-east-1

jobs:
    rotator-ci:
        name: Rotator CI
        runs-on: ubuntu-latest
        steps:
            - name: Check out current repository
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '>=1.20.0'

            - name: Compile Dagger pipeline
              working-directory: pipeline/dagger
              run: |
                  go mod tidy
                  go build -o pipeline-dagger
                  if [ -f "../../pipeline-dagger" ]; then rm ../../pipeline-dagger; fi
                  mv pipeline-dagger ../../pipeline-dagger


            - name: Compile
              run: |
                  ./pipeline-dagger lambda --compile --lambda-src=src/lambda/secrets-manager-rotator-go

            - name: Store Dagger pipeline
              uses: actions/upload-artifact@v3
              with:
                  name: pipeline
                  path: |
                      pipeline-dagger

            - name: Store Compiled Lambda
              uses: actions/upload-artifact@v3
              with:
                  name: compiled-rotator
                  path: |
                      output/lambda-bin/linux/amd64/secrets-manager-rotator-lambda

    compile-zip:
        needs: rotator-ci
        name: Generate Zip
        runs-on: ubuntu-latest
        steps:
            - name: Check out current repository
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '>=1.20.0'

            - name: Download Pipeline
              uses: actions/download-artifact@v3
              with:
                  name: pipeline

            - name: Download Compiled Rotator
              uses: actions/download-artifact@v3
              with:
                  name: compiled-rotator

            - name: Current files in WorkDir
              run: ls -ltrah

            - name: Make pipeline executable
              run: |
                  chmod +x pipeline-dagger

            - name: Generate Zip
              run: |
                  ./pipeline-dagger lambda --package-zip --existing-binary=secrets-manager-rotator-lambda

            - name: Store Zip File
              uses: actions/upload-artifact@v3
              with:
                  name: lambda-zip
                  path: |
                      output/lambda-zip/linux/amd64/secrets-manager-rotator-lambda.zip


    create-deployment-bucket:
        needs: [rotator-ci, compile-zip]
        name: Create Deployment Bucket
        runs-on: ubuntu-latest
        steps:
            - name: Check out current repository
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '>=1.20.0'

            - name: Download Pipeline
              uses: actions/download-artifact@v3
              with:
                  name: pipeline

            - name: Make pipeline executable
              run: |
                chmod +x pipeline-dagger

            - name: Deployment bucket plan
              run: |
                  ./pipeline-dagger infra --component=bucket --plan


            - name: Deployment bucket plan
              run: |
                  ./pipeline-dagger infra --component=bucket --deploy
